[workspace]
resolver = "2"
members = [
    "clients/runner",
    "clients/runtime",
    "clients/runtime/client",
    "clients/vault",
    "clients/wallet",
    "clients/service",
    "clients/stellar-relay-lib",
    "pallets/clients-info",
    "pallets/currency",
    "pallets/fee",
    "pallets/nomination",
    "pallets/oracle",
    "pallets/pooled-rewards",
    "pallets/reward-distribution",
    "pallets/staking",
    "pallets/stellar-relay",
    "pallets/vault-registry",
    "primitives",
    "pallets/*/rpc",
    "testchain/node",
    "testchain/runtime/mainnet",
    "testchain/runtime/testnet",
]
[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
# Sacrifice compile speed for execution speed by using optimization flags:
# https://doc.rust-lang.org/rustc/linker-plugin-lto.html
lto = "fat"
# https://doc.rust-lang.org/rustc/codegen-options/index.html#codegen-units
codegen-units = 1


[patch."https://github.com/paritytech/polkadot-sdk"]
frame-support = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
frame-support-procedural = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
frame-support-procedural-tools = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
frame-support-procedural-tools-derive = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
frame-system = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-core = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-externalities = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-io = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-runtime = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-std = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-storage = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-wasm-interface = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }

frame-benchmarking = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
frame-benchmarking-cli = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
frame-executive = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
frame-system-benchmarking = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
frame-system-rpc-runtime-api = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-aura = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-authorship = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-balances = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-grandpa = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-session = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-sudo = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-timestamp = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-transaction-payment = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-transaction-payment-rpc = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-allocator = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-basic-authorship = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-block-builder = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-chain-spec = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-chain-spec-derive = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-cli = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-client-api = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-client-db = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-consensus = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-consensus-aura = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-consensus-babe = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-consensus-epochs = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-consensus-manual-seal = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-consensus-slots = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-executor = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-executor-common = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-executor-wasmtime = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-consensus-grandpa = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-informant = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-keystore = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-network = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-network-bitswap = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-network-common = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-network-gossip = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-network-light = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-network-sync = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-network-transactions = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-offchain = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-proposer-metrics = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-rpc = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-rpc-api = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-rpc-server = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-rpc-spec-v2 = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-service = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-state-db = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-sysinfo = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-telemetry = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-tracing = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-tracing-proc-macro = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-transaction-pool = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-transaction-pool-api = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sc-utils = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-api = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-api-proc-macro = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-application-crypto = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-arithmetic = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-block-builder = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-blockchain = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-consensus = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-consensus-aura = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-consensus-babe = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-consensus-slots = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-core-hashing = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-core-hashing-proc-macro = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-database = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-debug-derive = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-consensus-grandpa = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-inherents = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-keyring = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-keystore = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-maybe-compressed-blob = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-offchain = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-panic-handler = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-rpc = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-runtime-interface = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-runtime-interface-proc-macro = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-session = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-staking = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-state-machine = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-tracing = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-transaction-pool = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-transaction-storage-proof = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-trie = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-timestamp = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-version = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-version-proc-macro = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-weights = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
substrate-build-script-utils = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
substrate-frame-rpc-system = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
substrate-prometheus-endpoint = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
substrate-wasm-builder = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
staging-xcm = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }

[patch.crates-io]
sp-core = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
sp-runtime = { git = "https://github.com/pendulum-chain/polkadot-sdk", branch = "main" }
 