[package]
authors = ["SatoshiPay"]
edition = "2018"
name = "spacewalk-primitives"
version = "1.2.0"

[dependencies]
bstringify = "0.1.2"
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false}
scale-info = {version = "2.1.1", default-features = false, features = ["derive"]}
serde = {version = "1.0.130", optional = true}

sp-core = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false}
sp-runtime = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false}
sp-std = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false}

[features]
default = ["std"]
std = [
  "serde",
  "codec/std",
  "sp-core/std",
  "sp-std/std",
  "sp-runtime/std",
]
