[package]
authors = ["Interlay <contact@interlay.io>"]
edition = "2021"
name = "module-vault-registry-rpc-runtime-api"
version = "1.0.15"

[dependencies]
codec = { workspace = true, features = ["derive", "max-encoded-len"]}
frame-support = { workspace = true }
module-oracle-rpc-runtime-api = {path = '../../../oracle/rpc/runtime-api', default-features = false}
sp-api = { workspace = true }
sp-std = { workspace = true }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-support/std",
	"module-oracle-rpc-runtime-api/std",
	"sp-api/std",
	"sp-std/std",
]
