[package]
authors = ["Interlay <contact@interlay.io>"]
edition = "2021"
name = "module-vault-registry-rpc-runtime-api"
version = "1.0.14"

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"]}
frame-support = {git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false}
module-oracle-rpc-runtime-api = {path = '../../../oracle/rpc/runtime-api', default-features = false}
sp-api = {git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false}
sp-std = {git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false}

[features]
default = ["std"]
std = [
  "codec/std",
  "frame-support/std",
  "sp-api/std",
  "sp-std/std",
  "module-oracle-rpc-runtime-api/std",
]
