# https://rust-lang.github.io/rustfmt/

comment_width = 120
edition = "2018"
hard_tabs = false
imports_granularity = "Crate"
max_width = 120
wrap_comments = true

# TODO: https://github.com/rust-lang/rustfmt/issues/3382#issuecomment-536034758
blank_lines_lower_bound = 0
