[package]
authors = ["Interlay <contact@interlay.io>"]
edition = "2021"
name = "module-oracle-rpc"
version = "1.0.3"

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"]}
jsonrpsee = {version = "0.16.0", features = ["server", "macros"]}
module-oracle-rpc-runtime-api = {path = "runtime-api"}
sp-api = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42"}
sp-blockchain = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42"}
sp-runtime = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42"}

primitives = { package = "spacewalk-primitives", path = "../../../primitives", default-features = false }
