[package]
authors = ["Interlay <contact@interlay.io>"]
edition = "2021"
name = "module-oracle-rpc"
version = "1.0.13"

[dependencies]
codec = { workspace = true, features = ["derive", "max-encoded-len"]}
jsonrpsee = {version = "0.16.0", features = ["client","server", "macros"]}
module-oracle-rpc-runtime-api = {path = "runtime-api"}
sp-api = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

primitives = { package = "spacewalk-primitives", path = "../../../primitives", default-features = false }
