
//! Autogenerated weights for redeem
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-03-09, STEPS: `100`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `MacBook-Pro`, CPU: `<UNKNOWN>`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/spacewalk-standalone
// benchmark
// pallet
// --chain=dev
// --pallet=redeem
// --extrinsic=*
// --steps=100
// --repeat=10
// --wasm-execution=compiled
// --output=pallets/redeem/src/default_weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for redeem.
pub trait WeightInfo {
	fn request_redeem() -> Weight;
	fn liquidation_redeem() -> Weight;
	fn execute_redeem() -> Weight;
	fn cancel_redeem_reimburse() -> Weight;
	fn cancel_redeem_retry() -> Weight;
	fn self_redeem() -> Weight;
	fn set_redeem_period() -> Weight;
	fn mint_tokens_for_reimbursed_redeem() -> Weight;
	fn rate_limit_update() -> Weight;
	fn minimum_transfer_amount_update() -> Weight;
}

/// Weights for redeem using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Redeem LimitVolumeAmount (r:1 w:0)
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Tokens Accounts (r:1 w:1)
	// Storage: Fee RedeemFee (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: Redeem RedeemMinimumTransferAmount (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:1)
	// Storage: VaultRewards TotalStake (r:1 w:1)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	// Storage: VaultRewards RewardPerToken (r:2 w:0)
	// Storage: Security Nonce (r:1 w:1)
	// Storage: System ParentHash (r:1 w:0)
	// Storage: VaultRegistry PremiumRedeemThreshold (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: Fee PremiumRedeemFee (r:1 w:0)
	// Storage: Security ActiveBlockCount (r:1 w:0)
	// Storage: Redeem RedeemPeriod (r:1 w:0)
	// Storage: Redeem RedeemRequests (r:0 w:1)
	fn request_redeem() -> Weight {
		// Minimum execution time: 77_000 nanoseconds.
		Weight::from_ref_time(81_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(20 as u64))
			.saturating_add(T::DbWeight::get().writes(8 as u64))
	}
	// Storage: Tokens Accounts (r:3 w:3)
	// Storage: Tokens TotalIssuance (r:1 w:1)
	// Storage: VaultRegistry LiquidationVault (r:1 w:1)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: System Account (r:2 w:1)
	fn liquidation_redeem() -> Weight {
		// Minimum execution time: 73_000 nanoseconds.
		Weight::from_ref_time(80_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(8 as u64))
			.saturating_add(T::DbWeight::get().writes(7 as u64))
	}
	// Storage: Redeem RedeemRequests (r:1 w:1)
	// Storage: StellarRelay IsPublicNetwork (r:1 w:0)
	// Storage: StellarRelay NewValidatorsEnactmentBlockHeight (r:1 w:0)
	// Storage: StellarRelay Validators (r:1 w:0)
	// Storage: StellarRelay Organizations (r:1 w:0)
	// Storage: Redeem LimitVolumeAmount (r:1 w:0)
	// Storage: VaultRewards TotalStake (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	fn execute_redeem() -> Weight {
		// Minimum execution time: 4_203_000 nanoseconds.
		Weight::from_ref_time(4_276_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(8 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Redeem RedeemRequests (r:1 w:1)
	// Storage: Redeem RedeemPeriod (r:1 w:0)
	// Storage: Security ActiveBlockCount (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: Fee PunishmentFee (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: VaultStaking TotalStake (r:1 w:0)
	// Storage: VaultRegistry PunishmentDelay (r:1 w:0)
	// Storage: VaultRewards TotalStake (r:1 w:0)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:0)
	fn cancel_redeem_reimburse() -> Weight {
		// Minimum execution time: 74_000 nanoseconds.
		Weight::from_ref_time(78_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(14 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Redeem RedeemRequests (r:1 w:1)
	// Storage: Redeem RedeemPeriod (r:1 w:0)
	// Storage: Security ActiveBlockCount (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: Fee PunishmentFee (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: VaultStaking TotalStake (r:1 w:0)
	// Storage: VaultRegistry PunishmentDelay (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:0)
	fn cancel_redeem_retry() -> Weight {
		// Minimum execution time: 64_000 nanoseconds.
		Weight::from_ref_time(66_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(12 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: Tokens Accounts (r:1 w:1)
	// Storage: Tokens TotalIssuance (r:1 w:1)
	// Storage: VaultRewards TotalStake (r:1 w:1)
	// Storage: VaultRewards RewardPerToken (r:2 w:1)
	// Storage: VaultRewards TotalRewards (r:1 w:1)
	// Storage: VaultRewards Stake (r:1 w:1)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	fn self_redeem() -> Weight {
		// Minimum execution time: 82_000 nanoseconds.
		Weight::from_ref_time(83_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(10 as u64))
			.saturating_add(T::DbWeight::get().writes(9 as u64))
	}
	// Storage: Redeem RedeemPeriod (r:0 w:1)
	fn set_redeem_period() -> Weight {
		// Minimum execution time: 11_000 nanoseconds.
		Weight::from_ref_time(12_000_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Redeem RedeemRequests (r:1 w:1)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:0)
	fn mint_tokens_for_reimbursed_redeem() -> Weight {
		// Minimum execution time: 52_000 nanoseconds.
		Weight::from_ref_time(54_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(7 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Redeem LimitVolumeAmount (r:0 w:1)
	// Storage: Redeem LimitVolumeCurrencyId (r:0 w:1)
	// Storage: Redeem IntervalLength (r:0 w:1)
	fn rate_limit_update() -> Weight {
		// Minimum execution time: 12_000 nanoseconds.
		Weight::from_ref_time(13_000_000 as u64)
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: Redeem RedeemMinimumTransferAmount (r:0 w:1)
	fn minimum_transfer_amount_update() -> Weight {
		// Minimum execution time: 11_000 nanoseconds.
		Weight::from_ref_time(11_000_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Redeem LimitVolumeAmount (r:1 w:0)
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Tokens Accounts (r:1 w:1)
	// Storage: Fee RedeemFee (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: Redeem RedeemMinimumTransferAmount (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:1)
	// Storage: VaultRewards TotalStake (r:1 w:1)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	// Storage: VaultRewards RewardPerToken (r:2 w:0)
	// Storage: Security Nonce (r:1 w:1)
	// Storage: System ParentHash (r:1 w:0)
	// Storage: VaultRegistry PremiumRedeemThreshold (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: Fee PremiumRedeemFee (r:1 w:0)
	// Storage: Security ActiveBlockCount (r:1 w:0)
	// Storage: Redeem RedeemPeriod (r:1 w:0)
	// Storage: Redeem RedeemRequests (r:0 w:1)
	fn request_redeem() -> Weight {
		// Minimum execution time: 77_000 nanoseconds.
		Weight::from_ref_time(81_000_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(20 as u64))
			.saturating_add(RocksDbWeight::get().writes(8 as u64))
	}
	// Storage: Tokens Accounts (r:3 w:3)
	// Storage: Tokens TotalIssuance (r:1 w:1)
	// Storage: VaultRegistry LiquidationVault (r:1 w:1)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: System Account (r:2 w:1)
	fn liquidation_redeem() -> Weight {
		// Minimum execution time: 73_000 nanoseconds.
		Weight::from_ref_time(80_000_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(8 as u64))
			.saturating_add(RocksDbWeight::get().writes(7 as u64))
	}
	// Storage: Redeem RedeemRequests (r:1 w:1)
	// Storage: StellarRelay IsPublicNetwork (r:1 w:0)
	// Storage: StellarRelay NewValidatorsEnactmentBlockHeight (r:1 w:0)
	// Storage: StellarRelay Validators (r:1 w:0)
	// Storage: StellarRelay Organizations (r:1 w:0)
	// Storage: Redeem LimitVolumeAmount (r:1 w:0)
	// Storage: VaultRewards TotalStake (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	fn execute_redeem() -> Weight {
		// Minimum execution time: 4_203_000 nanoseconds.
		Weight::from_ref_time(4_276_000_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(8 as u64))
			.saturating_add(RocksDbWeight::get().writes(2 as u64))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Redeem RedeemRequests (r:1 w:1)
	// Storage: Redeem RedeemPeriod (r:1 w:0)
	// Storage: Security ActiveBlockCount (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: Fee PunishmentFee (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: VaultStaking TotalStake (r:1 w:0)
	// Storage: VaultRegistry PunishmentDelay (r:1 w:0)
	// Storage: VaultRewards TotalStake (r:1 w:0)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:0)
	fn cancel_redeem_reimburse() -> Weight {
		// Minimum execution time: 74_000 nanoseconds.
		Weight::from_ref_time(78_000_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(14 as u64))
			.saturating_add(RocksDbWeight::get().writes(3 as u64))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Redeem RedeemRequests (r:1 w:1)
	// Storage: Redeem RedeemPeriod (r:1 w:0)
	// Storage: Security ActiveBlockCount (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: Fee PunishmentFee (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: VaultStaking TotalStake (r:1 w:0)
	// Storage: VaultRegistry PunishmentDelay (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:0)
	fn cancel_redeem_retry() -> Weight {
		// Minimum execution time: 64_000 nanoseconds.
		Weight::from_ref_time(66_000_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(12 as u64))
			.saturating_add(RocksDbWeight::get().writes(3 as u64))
	}
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: Tokens Accounts (r:1 w:1)
	// Storage: Tokens TotalIssuance (r:1 w:1)
	// Storage: VaultRewards TotalStake (r:1 w:1)
	// Storage: VaultRewards RewardPerToken (r:2 w:1)
	// Storage: VaultRewards TotalRewards (r:1 w:1)
	// Storage: VaultRewards Stake (r:1 w:1)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	fn self_redeem() -> Weight {
		// Minimum execution time: 82_000 nanoseconds.
		Weight::from_ref_time(83_000_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(10 as u64))
			.saturating_add(RocksDbWeight::get().writes(9 as u64))
	}
	// Storage: Redeem RedeemPeriod (r:0 w:1)
	fn set_redeem_period() -> Weight {
		// Minimum execution time: 11_000 nanoseconds.
		Weight::from_ref_time(12_000_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Redeem RedeemRequests (r:1 w:1)
	// Storage: VaultRegistry Vaults (r:1 w:1)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:0)
	fn mint_tokens_for_reimbursed_redeem() -> Weight {
		// Minimum execution time: 52_000 nanoseconds.
		Weight::from_ref_time(54_000_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(7 as u64))
			.saturating_add(RocksDbWeight::get().writes(2 as u64))
	}
	// Storage: Redeem LimitVolumeAmount (r:0 w:1)
	// Storage: Redeem LimitVolumeCurrencyId (r:0 w:1)
	// Storage: Redeem IntervalLength (r:0 w:1)
	fn rate_limit_update() -> Weight {
		// Minimum execution time: 12_000 nanoseconds.
		Weight::from_ref_time(13_000_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(3 as u64))
	}
	// Storage: Redeem RedeemMinimumTransferAmount (r:0 w:1)
	fn minimum_transfer_amount_update() -> Weight {
		// Minimum execution time: 11_000 nanoseconds.
		Weight::from_ref_time(11_000_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
}