// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for nomination
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-10, STEPS: `100`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/spacewalk-standalone
// benchmark
// pallet
// --chain=dev
// --pallet=nomination
// --extrinsic=*
// --steps=100
// --repeat=10
// --wasm-execution=compiled
// --output=pallets/nomination/src/default_weights.rs
// --template=.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for nomination.
pub trait WeightInfo {
	fn set_nomination_enabled() -> Weight;
	fn opt_in_to_nomination() -> Weight;
	fn opt_out_of_nomination() -> Weight;
	fn deposit_collateral() -> Weight;
	fn withdraw_collateral() -> Weight;
}

/// Weights for nomination using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Nomination NominationEnabled (r:0 w:1)
	fn set_nomination_enabled() -> Weight {
		(3_520_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Nomination NominationEnabled (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:0)
	// Storage: Nomination Vaults (r:1 w:1)
	fn opt_in_to_nomination() -> Weight {
		(28_208_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Nomination Vaults (r:1 w:1)
	// Storage: VaultStaking Nonce (r:1 w:1)
	// Storage: VaultStaking TotalCurrentStake (r:2 w:2)
	// Storage: VaultStaking Stake (r:2 w:2)
	// Storage: VaultStaking SlashPerToken (r:2 w:0)
	// Storage: VaultStaking SlashTally (r:2 w:2)
	// Storage: VaultRegistry Vaults (r:1 w:0)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: Oracle Aggregate (r:1 w:0)
	// Storage: VaultStaking TotalStake (r:2 w:2)
	// Storage: VaultStaking RewardTally (r:4 w:4)
	// Storage: VaultStaking RewardPerToken (r:4 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	fn opt_out_of_nomination() -> Weight {
		(149_630_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(25 as Weight))
			.saturating_add(T::DbWeight::get().writes(15 as Weight))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Nomination NominationEnabled (r:1 w:0)
	// Storage: Nomination Vaults (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:1)
	// Storage: VaultStaking Stake (r:2 w:1)
	// Storage: VaultStaking SlashPerToken (r:1 w:0)
	// Storage: VaultStaking SlashTally (r:2 w:1)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: VaultRegistry PremiumRedeemThreshold (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:0)
	// Storage: VaultRewards RewardPerToken (r:2 w:0)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	// Storage: VaultRewards TotalRewards (r:2 w:2)
	// Storage: VaultStaking RewardPerToken (r:2 w:2)
	// Storage: VaultStaking TotalStake (r:1 w:1)
	// Storage: VaultStaking RewardTally (r:2 w:2)
	// Storage: Tokens Accounts (r:2 w:2)
	// Storage: System Account (r:1 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: VaultRegistry SystemCollateralCeiling (r:1 w:0)
	fn deposit_collateral() -> Weight {
		(157_557_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(29 as Weight))
			.saturating_add(T::DbWeight::get().writes(15 as Weight))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:1)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: Oracle Aggregate (r:1 w:0)
	// Storage: Nomination NominationEnabled (r:1 w:0)
	// Storage: Nomination Vaults (r:1 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: VaultRewards Stake (r:1 w:0)
	// Storage: VaultRewards RewardPerToken (r:2 w:0)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	// Storage: VaultRewards TotalRewards (r:2 w:2)
	// Storage: VaultStaking RewardPerToken (r:2 w:2)
	// Storage: VaultStaking Stake (r:1 w:1)
	// Storage: VaultStaking SlashPerToken (r:1 w:0)
	// Storage: VaultStaking SlashTally (r:1 w:1)
	// Storage: VaultStaking TotalStake (r:1 w:1)
	// Storage: VaultStaking RewardTally (r:2 w:2)
	// Storage: Tokens Accounts (r:2 w:2)
	// Storage: System Account (r:1 w:0)
	fn withdraw_collateral() -> Weight {
		(166_619_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(27 as Weight))
			.saturating_add(T::DbWeight::get().writes(15 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Nomination NominationEnabled (r:0 w:1)
	fn set_nomination_enabled() -> Weight {
		(3_520_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Nomination NominationEnabled (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:0)
	// Storage: Nomination Vaults (r:1 w:1)
	fn opt_in_to_nomination() -> Weight {
		(28_208_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Nomination Vaults (r:1 w:1)
	// Storage: VaultStaking Nonce (r:1 w:1)
	// Storage: VaultStaking TotalCurrentStake (r:2 w:2)
	// Storage: VaultStaking Stake (r:2 w:2)
	// Storage: VaultStaking SlashPerToken (r:2 w:0)
	// Storage: VaultStaking SlashTally (r:2 w:2)
	// Storage: VaultRegistry Vaults (r:1 w:0)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: Oracle Aggregate (r:1 w:0)
	// Storage: VaultStaking TotalStake (r:2 w:2)
	// Storage: VaultStaking RewardTally (r:4 w:4)
	// Storage: VaultStaking RewardPerToken (r:4 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	fn opt_out_of_nomination() -> Weight {
		(149_630_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(25 as Weight))
			.saturating_add(RocksDbWeight::get().writes(15 as Weight))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: Nomination NominationEnabled (r:1 w:0)
	// Storage: Nomination Vaults (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:1)
	// Storage: VaultStaking Stake (r:2 w:1)
	// Storage: VaultStaking SlashPerToken (r:1 w:0)
	// Storage: VaultStaking SlashTally (r:2 w:1)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: VaultRegistry PremiumRedeemThreshold (r:1 w:0)
	// Storage: VaultRewards Stake (r:1 w:0)
	// Storage: VaultRewards RewardPerToken (r:2 w:0)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	// Storage: VaultRewards TotalRewards (r:2 w:2)
	// Storage: VaultStaking RewardPerToken (r:2 w:2)
	// Storage: VaultStaking TotalStake (r:1 w:1)
	// Storage: VaultStaking RewardTally (r:2 w:2)
	// Storage: Tokens Accounts (r:2 w:2)
	// Storage: System Account (r:1 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: VaultRegistry SystemCollateralCeiling (r:1 w:0)
	fn deposit_collateral() -> Weight {
		(157_557_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(29 as Weight))
			.saturating_add(RocksDbWeight::get().writes(15 as Weight))
	}
	// Storage: Security ParachainStatus (r:1 w:0)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultRegistry Vaults (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:1)
	// Storage: VaultRegistry SecureCollateralThreshold (r:1 w:0)
	// Storage: Oracle Aggregate (r:1 w:0)
	// Storage: Nomination NominationEnabled (r:1 w:0)
	// Storage: Nomination Vaults (r:1 w:0)
	// Storage: VaultRegistry TotalUserVaultCollateral (r:1 w:1)
	// Storage: VaultRewards Stake (r:1 w:0)
	// Storage: VaultRewards RewardPerToken (r:2 w:0)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	// Storage: VaultRewards TotalRewards (r:2 w:2)
	// Storage: VaultStaking RewardPerToken (r:2 w:2)
	// Storage: VaultStaking Stake (r:1 w:1)
	// Storage: VaultStaking SlashPerToken (r:1 w:0)
	// Storage: VaultStaking SlashTally (r:1 w:1)
	// Storage: VaultStaking TotalStake (r:1 w:1)
	// Storage: VaultStaking RewardTally (r:2 w:2)
	// Storage: Tokens Accounts (r:2 w:2)
	// Storage: System Account (r:1 w:0)
	fn withdraw_collateral() -> Weight {
		(166_619_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(27 as Weight))
			.saturating_add(RocksDbWeight::get().writes(15 as Weight))
	}
}