
//! Autogenerated weights for `pallet_stellar_relay`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-05, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/spacewalk-standalone
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_stellar_relay
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// pallets/stellar-relay/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_stellar_relay`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_stellar_relay::WeightInfo for WeightInfo<T> {
	// Storage: StellarRelay Validators (r:0 w:1)
	// Storage: StellarRelay Organizations (r:0 w:1)
	fn update_tier_1_validator_set_benchmark() -> Weight {
		(36_000_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}
