[package]
name = "module-redeem-rpc"
version = "1.0.13"
authors = ["Interlay <contact@interlay.io>"]
edition = "2021"

[dependencies]
codec = { workspace = true, default-features = true }
jsonrpsee = { version = "0.16.0", features = ["client", "server", "macros"] }
sp-runtime = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
module-redeem-rpc-runtime-api = { path = "runtime-api" }
