#!/bin/bash
##### arguments:
#####   * reason = what the command is for
#####   * sub_cmd = the actual sub command
#####      e.g. build --lib
#####   * options = additional options of the sub command
#####      e.g. -- -W clippy::all
reason=$1
sub_cmd=$2
options=$3

echo "------------------------------------------------------"
echo "--------- Checking" $reason "on all packages ---------"
echo "------------------------------------------------------"

cargo $sub_cmd -p spacewalk-primitives --all-features $options

echo "---------------------  Checks" $reason "on all pallets"
cargo $sub_cmd -p clients-info --all-features
echo "--  Excluding testing-utils feature of pallet currency;"
echo "-------------------------  that is for nightly version."
cargo $sub_cmd -p currency --features std,testing-constants,try-runtime,runtime-benchmarks $options
cargo $sub_cmd -p fee --all-features $options
cargo $sub_cmd -p issue --all-features $options
cargo $sub_cmd -p nomination --all-features $options
cargo $sub_cmd -p oracle --all-features $options
cargo $sub_cmd -p pooled-rewards --all-features $options
cargo $sub_cmd -p redeem --all-features $options
cargo $sub_cmd -p replace --all-features $options
cargo $sub_cmd -p reward-distribution --all-features $options
cargo $sub_cmd -p security --all-features $options
cargo $sub_cmd -p staking --all-features $options
cargo $sub_cmd -p stellar-relay --all-features $options
cargo $sub_cmd -p vault-registry --all-features $options

echo "-----------------  Checks" $reason "for pallets with rpc"
cargo $sub_cmd -p module-issue-rpc --all-features $options
cargo $sub_cmd -p module-oracle-rpc --all-features $options
cargo $sub_cmd -p module-redeem-rpc --all-features $options
cargo $sub_cmd -p module-replace-rpc --all-features $options
cargo $sub_cmd -p module-vault-registry-rpc --all-features $options
cargo $sub_cmd -p module-issue-rpc-runtime-api --all-features $options
cargo $sub_cmd -p module-oracle-rpc-runtime-api --all-features $options
cargo $sub_cmd -p module-redeem-rpc-runtime-api --all-features $options
cargo $sub_cmd -p module-replace-rpc-runtime-api --all-features $options
cargo $sub_cmd -p module-vault-registry-rpc-runtime-api --all-features $options

echo "-------  Checks" $reason "on packages in clients directory"
cargo $sub_cmd -p runner --all-features $options
cargo $sub_cmd -p runtime --all-features $options
cargo $sub_cmd -p service --all-features $options
cargo $sub_cmd -p stellar-relay-lib --all-features $options
cargo $sub_cmd -p subxt-client --all-features $options
cargo $sub_cmd -p vault --all-features $options
cargo $sub_cmd -p wallet --all-features $options

echo "-------------------------- Checks" $reason "from testchain"
cargo $sub_cmd -p spacewalk-runtime-standalone-mainnet --all-features $options
cargo $sub_cmd -p spacewalk-runtime-standalone-testnet --all-features $options
cargo $sub_cmd -p spacewalk-standalone --all-features $options