#!/bin/bash
set -e

##### Executes the command to ALL packages of this project.
##### An exception is the package `subxt-client`, as it needs the package `runtime` for it to work.
##### The currently supported (and tested) commands are: check and clippy
##### arguments:
#####   * reason = what the command is for
#####   * sub_cmd = the actual sub command. For commands separated by spaces, enclose with ""
#####     e.g. "build --lib"
#####          "+nightly check"
#####   * options = additional options of the sub command. If separated by spaces, enclose with ""
#####     e.g. "-- -W clippy::all"
reason=$1
sub_cmd=$2
options=$3

echo "------------------------------------------------------------------------"
echo "------------------------------------------------------------------------"
echo "Checking $reason on all packages"
echo "------------------------------------------------------------------------"
echo "------------------------------------------------------------------------"

cargo $sub_cmd -p spacewalk-primitives --all-features $options

# run the pallets
./scripts/cmd-pallets "$reason" "$sub_cmd" "$options"

# run the clients
./scripts/cmd-clients "$reason" "$sub_cmd" "$options"

# run the others
./scripts/cmd-others $reason $sub_cmd $options

echo "------------------------------------------------------------------------"
echo "Checks $reason on the vault"
echo "------------------------------------------------------------------------"
cargo $sub_cmd -p vault --all-features $options