#!/bin/bash
set -e

reason=$1
sub_cmd=$2
options=$3

echo "------------------------------------------------------------------------"
echo "Checks $reason on all pallets"
echo "------------------------------------------------------------------------"
cargo $sub_cmd -p clients-info --all-features $options

if [[ $sub_cmd == *"nightly"* ]]; then
  cargo $sub_cmd -p currency $options
else
  echo "------------------------------------------------------------------------"
  echo "     Excluding testing-utils feature of pallet currency;"
  echo "     that is for nightly version."
  echo "------------------------------------------------------------------------"
  cargo $sub_cmd -p currency --features std,testing-constants,try-runtime,runtime-benchmarks $options
fi

cargo $sub_cmd -p fee --all-features $options
cargo $sub_cmd -p issue --all-features $options
cargo $sub_cmd -p nomination --all-features $options
cargo $sub_cmd -p oracle --all-features $options
cargo $sub_cmd -p pooled-rewards --all-features $options
cargo $sub_cmd -p redeem --all-features $options
cargo $sub_cmd -p replace --all-features $options
cargo $sub_cmd -p reward --all-features $options
cargo $sub_cmd -p reward-distribution --all-features $options
cargo $sub_cmd -p security --all-features $options
cargo $sub_cmd -p staking --all-features $options
cargo $sub_cmd -p stellar-relay --all-features $options
cargo $sub_cmd -p vault-registry --all-features $options

if [[ $reason != "test"* ]]; then
  echo "------------------------------------------------------------------------"
  echo "Checks $reason for pallets with rpc"
  echo "------------------------------------------------------------------------"
  cargo $sub_cmd -p module-issue-rpc --all-features $options
  cargo $sub_cmd -p module-oracle-rpc --all-features $options
  cargo $sub_cmd -p module-redeem-rpc --all-features $options
  cargo $sub_cmd -p module-replace-rpc --all-features $options
  cargo $sub_cmd -p module-vault-registry-rpc --all-features $options
  cargo $sub_cmd -p module-issue-rpc-runtime-api --all-features $options
  cargo $sub_cmd -p module-oracle-rpc-runtime-api --all-features $options
  cargo $sub_cmd -p module-redeem-rpc-runtime-api --all-features $options
  cargo $sub_cmd -p module-replace-rpc-runtime-api --all-features $options
  cargo $sub_cmd -p module-vault-registry-rpc-runtime-api --all-features $options
fi