// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for fee
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-10, STEPS: `100`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/spacewalk-standalone
// benchmark
// pallet
// --chain=dev
// --pallet=fee
// --extrinsic=*
// --steps=100
// --repeat=10
// --wasm-execution=compiled
// --output=pallets/fee/src/default_weights.rs
// --template=.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for fee.
pub trait WeightInfo {
	fn withdraw_rewards() -> Weight;
	fn set_issue_fee() -> Weight;
	fn set_issue_griefing_collateral() -> Weight;
	fn set_redeem_fee() -> Weight;
	fn set_premium_redeem_fee() -> Weight;
	fn set_punishment_fee() -> Weight;
	fn set_replace_griefing_collateral() -> Weight;
}

/// Weights for fee using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: VaultRewards Stake (r:1 w:0)
	// Storage: VaultRewards RewardPerToken (r:2 w:0)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	// Storage: VaultRewards TotalRewards (r:2 w:2)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: VaultStaking Stake (r:1 w:1)
	// Storage: VaultStaking SlashPerToken (r:1 w:0)
	// Storage: VaultStaking SlashTally (r:1 w:1)
	// Storage: VaultStaking TotalStake (r:1 w:1)
	// Storage: VaultStaking RewardPerToken (r:2 w:0)
	// Storage: VaultStaking RewardTally (r:2 w:2)
	// Storage: VaultStaking TotalRewards (r:2 w:2)
	fn withdraw_rewards() -> Weight {
		(89_124_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(19 as Weight))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
	}
	// Storage: Fee IssueFee (r:0 w:1)
	fn set_issue_fee() -> Weight {
		(3_222_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee IssueGriefingCollateral (r:0 w:1)
	fn set_issue_griefing_collateral() -> Weight {
		(3_169_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee RedeemFee (r:0 w:1)
	fn set_redeem_fee() -> Weight {
		(3_322_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee PremiumRedeemFee (r:0 w:1)
	fn set_premium_redeem_fee() -> Weight {
		(3_057_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee PunishmentFee (r:0 w:1)
	fn set_punishment_fee() -> Weight {
		(3_073_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee ReplaceGriefingCollateral (r:0 w:1)
	fn set_replace_griefing_collateral() -> Weight {
		(3_025_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: VaultRewards Stake (r:1 w:0)
	// Storage: VaultRewards RewardPerToken (r:2 w:0)
	// Storage: VaultRewards RewardTally (r:2 w:2)
	// Storage: VaultRewards TotalRewards (r:2 w:2)
	// Storage: VaultStaking Nonce (r:1 w:0)
	// Storage: VaultStaking TotalCurrentStake (r:1 w:0)
	// Storage: VaultStaking Stake (r:1 w:1)
	// Storage: VaultStaking SlashPerToken (r:1 w:0)
	// Storage: VaultStaking SlashTally (r:1 w:1)
	// Storage: VaultStaking TotalStake (r:1 w:1)
	// Storage: VaultStaking RewardPerToken (r:2 w:0)
	// Storage: VaultStaking RewardTally (r:2 w:2)
	// Storage: VaultStaking TotalRewards (r:2 w:2)
	fn withdraw_rewards() -> Weight {
		(89_124_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(19 as Weight))
			.saturating_add(RocksDbWeight::get().writes(11 as Weight))
	}
	// Storage: Fee IssueFee (r:0 w:1)
	fn set_issue_fee() -> Weight {
		(3_222_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee IssueGriefingCollateral (r:0 w:1)
	fn set_issue_griefing_collateral() -> Weight {
		(3_169_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee RedeemFee (r:0 w:1)
	fn set_redeem_fee() -> Weight {
		(3_322_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee PremiumRedeemFee (r:0 w:1)
	fn set_premium_redeem_fee() -> Weight {
		(3_057_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee PunishmentFee (r:0 w:1)
	fn set_punishment_fee() -> Weight {
		(3_073_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Fee ReplaceGriefingCollateral (r:0 w:1)
	fn set_replace_griefing_collateral() -> Weight {
		(3_025_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}