[package]
name = "module-redeem-rpc-runtime-api"
version = "1.0.13"
authors = ["Interlay <contact@interlay.io>"]
edition = "2021"

[dependencies]
codec = { workspace = true, features = ["derive", "max-encoded-len"] }
frame-support = { workspace = true }
sp-api = { workspace = true }
sp-std = { workspace = true }

[features]
default = [ "std" ]
std = [ "codec/std", "frame-support/std", "sp-api/std", "sp-std/std" ]
