name: Triggers the CI pipeline in GitLab
on:
  pull_request:
    branches:
      - '**' # every branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger job
        uses: appleboy/gitlab-ci-action@master
        with:
          host: "https://gitlab.com"
          token: ${{ secrets.GITLABAPI }}
          debug: true
          project_id: 51267165
          ref: development