name: 'Other Necessary Installations'

inputs:
  token:
    description: 'A Github PAT'
    required: true

runs:
    using: "composite"
    steps:
      - name: Install package
        shell: bash
        run: |
          sudo docker image prune --all --force
          echo 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: Install Rust and Rust-src
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          rustup update
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src

#      - name: Use Cache
#        uses: Swatinem/rust-cache@v2
#        with:
#          cache-on-failure: true
#          key: "ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}"
#          shared-key: "shared"

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ inputs.token }}